# --- Стадия установки зависимостей для серврной части ---
# 1. Установка базового образа
FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine AS backend-build

# 2. Установка рабочей директории
WORKDIR /app

# 3. Копирование файлов проекта 
COPY src/backend/dotnet .

# 4. Публикация проекта
RUN dotnet publish Web/Web.csproj --configuration Release -o /publish

# --- Стадия запуска серврной части ---
# 1. Установка финального образа
FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine AS backend-final

# 2. Установка сurl
RUN apk add --no-cache curl=8.17.0-r1

# 3. Установка рабочей директории
WORKDIR /app

# 4. Копирование собранного приложения
COPY --from=backend-build /publish /app