services:
  database:
    image: ${POSTGRES_IMAGE}
    container_name: eventor-database
    restart: unless-stopped
    environment:
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ../${POSTGRES_DATA}:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -p 5432"]
      start_period: 15s
      interval: 3s
      timeout: 3s
      retries: 3
    networks:
      - eventor-test-network

  database-interface:
    image: ${PGADMIN_IMAGE}
    container_name: eventor-database-interface
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    volumes:
      - ../${PGADMIN_CONFIG}/servers.json:/pgadmin4/servers.json:ro
      - ../${PGADMIN_DATA}:/var/lib/pgadmin
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:80 || exit 1"]
      start_period: 90s
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      database:
        condition: service_healthy
    networks:
      - eventor-test-network

  web-server:
    image: ${DOCKER_HUB_USER}/${DOCKER_WEBSERVER_REPOSITORY}:latest
    container_name: eventor-webserver
    restart: unless-stopped
    ports:
      - "${WEBSERVER_PORT}:80"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/ || exit 1"]
      start_period: 15s
      interval: 5s  
      timeout: 5s
      retries: 5
    networks:
      - eventor-test-network

  backend:
    image: ${DOCKER_HUB_USER}/${DOCKER_BACKEND_REPOSITORY}:latest
    container_name: eventor-backend
    restart: unless-stopped
    ports:
      - "${BACKEND_PORT}:8080"
    environment:
      - "ConnectionStrings__Default=Host=eventor-database;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/ || exit 1"]
      start_period: 15s
      interval: 5s  
      timeout: 5s
      retries: 5
    networks:
      - eventor-test-network

networks:
  eventor-test-network:                  
    driver: bridge