CONTEXT=../../..
BACKEND_PATH=src/backend
FRONTEND_PATH=src/frontend
DOCKER_PATH=infra/cicd/docker
NGINX_PATH=shared/nginx

POSTGRES_PORT=5432
POSTGRES_DB=eventor
POSTGRES_USER=postgres
POSTGRES_PASSWORD=postgres

COMPOSE_PROJECT_NAME=eventor-cicd-stand