CONTEXT=../../..
BACKEND_PATH=src/backend
FRONTEND_PATH=src/frontend
DATABASE_PATH=src/database
DOCKER_PATH=infra/local/docker

POSTGRES_PORT=5432
POSTGRES_DB=eventor
POSTGRES_USER=postgres
POSTGRES_PASSWORD=postgres

PGADMIN_DEFAULT_EMAIL=admin@example.com
PGADMIN_DEFAULT_PASSWORD=admin

COMPOSE_PROJECT_NAME=eventor-local-stand