# 1. Установка базового образа
FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine

# 2. Установка рабочей директории
WORKDIR /app

# 3. Копирование .csproj файла (# TODO: изменить путь к файлу проекта )
COPY src/backend/dotnet/Eventor.csproj ./ 

# 4. Установка зависимостей и удаление .csproj файла
RUN dotnet restore Eventor.csproj --verbosity normal