# 1. Установка базового образа
FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine

# 2. Установка рабочей директории
WORKDIR /app

# 3. Копирование .sln файла 
COPY src/backend/dotnet/Eventor.sln ./ 

# 4. Установка зависимостей
RUN dotnet restore Eventor.sln --verbosity normal