server {
    listen 80;
    server_name localhost eventor.ru www.eventor.ru;

    root /var/www/eventor/browser;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
