# 1. Установка базового образа для веб сервера
FROM node:18-alpine

# 2. Установка рабочей директории
WORKDIR /app

# 3. Копирование файлов фронтенда
COPY src/frontend/typescript/ ./

# 4. Установка зависимостей
RUN npm install