# 1. Установка базового образа для веб сервера
FROM node:18-alpine

# 2. Установка рабочей директории
WORKDIR /app

# 3. Установка Angular CLI
RUN npm install -g @angular/cli

# 4. Копирование файлов фронтенда
COPY src/frontend/angular/ ./

# 5. Установка зависимостей
RUN npm install

# 6. Удержание контейнера запущенным
CMD ["tail", "-f", "/dev/null"]