# 1. Установка базового образа
FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine

# 2. Установка рабочей директории
WORKDIR /app

# 3. Копирование .csproj файла (# TODO: изменить путь к файлу проекта )
COPY src/backend/dotnet/ ./

# 4. Установка зависимостей 
RUN dotnet restore Eventor.sln --verbosity normal

# 5. Удержание контейнера запущенным
CMD ["tail", "-f", "/dev/null"]