// <auto-generated />
using System;
using DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(EventorDbContext))]
    partial class EventorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "gender", new[] { "Мужчина", "Женщина" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "registration_type", new[] { "Cтандартный", "VIP", "Организатор" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "user_role", new[] { "Администратор", "Зарегистрированный пользователь", "Гость" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DataAccess.Models.DayDb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("day_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<Guid>("MenuId")
                        .HasColumnType("uuid")
                        .HasColumnName("menu_id");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("integer")
                        .HasColumnName("sequence_number");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("PK_days");

                    b.HasIndex("EventId");

                    b.HasIndex("MenuId")
                        .IsUnique();

                    b.ToTable("days", null, t =>
                        {
                            t.HasCheckConstraint("CK_Days_DescriptionLength", "char_length(description) <= 8192");

                            t.HasCheckConstraint("CK_Days_SequenceNumber_Positive", "\"sequence_number\" > 0");
                        });
                });

            modelBuilder.Entity("DataAccess.Models.EventDb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<int>("DaysCount")
                        .HasColumnType("integer")
                        .HasColumnName("days_count");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<double>("Percent")
                        .HasColumnType("numeric")
                        .HasColumnName("percent");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("PK_events");

                    b.HasIndex("LocationId");

                    b.ToTable("events", null, t =>
                        {
                            t.HasCheckConstraint("CK_Event_DaysCount", "\"days_count\" >= 0");

                            t.HasCheckConstraint("CK_Event_DescriptionLength", "char_length(description) <= 8192");

                            t.HasCheckConstraint("CK_Event_Percent", "\"percent\" >= 0");
                        });
                });

            modelBuilder.Entity("DataAccess.Models.FeedbackDb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("feedback_id");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<int>("Rate")
                        .HasColumnType("integer")
                        .HasColumnName("rate");

                    b.Property<Guid>("RegistrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("registration_id");

                    b.HasKey("Id")
                        .HasName("PK_feedbacks");

                    b.HasIndex("RegistrationId");

                    b.ToTable("feedbacks", null, t =>
                        {
                            t.HasCheckConstraint("CK_Feedback_CommentLength", "char_length(comment) <= 4096");

                            t.HasCheckConstraint("CK_Feedback_Rate", "\"rate\" >= 1 AND \"rate\" <= 5");
                        });
                });

            modelBuilder.Entity("DataAccess.Models.ItemDb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric")
                        .HasColumnName("cost");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("PK_items");

                    b.ToTable("items", null, t =>
                        {
                            t.HasCheckConstraint("CK_Items_Cost", "\"cost\" >= 0");
                        });
                });

            modelBuilder.Entity("DataAccess.Models.LocationDb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric")
                        .HasColumnName("cost");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("PK_locations");

                    b.ToTable("locations", null, t =>
                        {
                            t.HasCheckConstraint("CK_Location_Capacity", "\"capacity\" >= 0");

                            t.HasCheckConstraint("CK_Location_Cost", "\"cost\" >= 0");
                        });
                });

            modelBuilder.Entity("DataAccess.Models.MenuDb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("menu_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("PK_menu");

                    b.ToTable("menu", null, t =>
                        {
                            t.HasCheckConstraint("CK_Menu_DescriptionLength", "char_length(description) <= 8192");
                        });
                });

            modelBuilder.Entity("DataAccess.Models.MenuItemDb", b =>
                {
                    b.Property<Guid>("MenuId")
                        .HasColumnType("uuid")
                        .HasColumnName("menu_id");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<int>("Amount")
                        .HasColumnType("integer")
                        .HasColumnName("amount");

                    b.HasKey("MenuId", "ItemId")
                        .HasName("PK_menu_items");

                    b.HasIndex("ItemId");

                    b.ToTable("menu_items", (string)null);
                });

            modelBuilder.Entity("DataAccess.Models.ParticipationDb", b =>
                {
                    b.Property<Guid>("DayId")
                        .HasColumnType("uuid")
                        .HasColumnName("day_id");

                    b.Property<Guid>("RegistrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("registration_id");

                    b.HasKey("DayId", "RegistrationId")
                        .HasName("PK_participation");

                    b.HasIndex("RegistrationId");

                    b.ToTable("participation", (string)null);
                });

            modelBuilder.Entity("DataAccess.Models.RegistrationDb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("registration_id");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<bool>("Payment")
                        .HasColumnType("boolean")
                        .HasColumnName("payment");

                    b.Property<int>("Type")
                        .HasColumnType("registration_type")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK_registrations");

                    b.HasIndex("UserId");

                    b.HasIndex("EventId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_registrations_event_user");

                    b.ToTable("registrations", (string)null);
                });

            modelBuilder.Entity("DataAccess.Models.UserDb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("Gender")
                        .HasColumnType("gender")
                        .HasColumnName("gender");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("phone");

                    b.Property<int>("Role")
                        .HasColumnType("user_role")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("PK_users");

                    b.HasIndex("Phone")
                        .IsUnique()
                        .HasDatabaseName("IX_users_phone");

                    b.HasIndex("Role")
                        .HasDatabaseName("IX_users_role");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("DataAccess.Models.DayDb", b =>
                {
                    b.HasOne("DataAccess.Models.EventDb", "Event")
                        .WithMany("Days")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Models.MenuDb", "Menu")
                        .WithOne("Day")
                        .HasForeignKey("DataAccess.Models.DayDb", "MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("DataAccess.Models.EventDb", b =>
                {
                    b.HasOne("DataAccess.Models.LocationDb", "Location")
                        .WithMany("Events")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("DataAccess.Models.FeedbackDb", b =>
                {
                    b.HasOne("DataAccess.Models.RegistrationDb", "Registration")
                        .WithMany("Feedbacks")
                        .HasForeignKey("RegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Registration");
                });

            modelBuilder.Entity("DataAccess.Models.MenuItemDb", b =>
                {
                    b.HasOne("DataAccess.Models.ItemDb", "Item")
                        .WithMany("MenuItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccess.Models.MenuDb", "Menu")
                        .WithMany("MenuItems")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("DataAccess.Models.ParticipationDb", b =>
                {
                    b.HasOne("DataAccess.Models.DayDb", "Day")
                        .WithMany("Participations")
                        .HasForeignKey("DayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Models.RegistrationDb", "Registration")
                        .WithMany("Participations")
                        .HasForeignKey("RegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Day");

                    b.Navigation("Registration");
                });

            modelBuilder.Entity("DataAccess.Models.RegistrationDb", b =>
                {
                    b.HasOne("DataAccess.Models.EventDb", "Event")
                        .WithMany("Registrations")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Models.UserDb", "User")
                        .WithMany("Registrations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataAccess.Models.DayDb", b =>
                {
                    b.Navigation("Participations");
                });

            modelBuilder.Entity("DataAccess.Models.EventDb", b =>
                {
                    b.Navigation("Days");

                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("DataAccess.Models.ItemDb", b =>
                {
                    b.Navigation("MenuItems");
                });

            modelBuilder.Entity("DataAccess.Models.LocationDb", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("DataAccess.Models.MenuDb", b =>
                {
                    b.Navigation("Day")
                        .IsRequired();

                    b.Navigation("MenuItems");
                });

            modelBuilder.Entity("DataAccess.Models.RegistrationDb", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("Participations");
                });

            modelBuilder.Entity("DataAccess.Models.UserDb", b =>
                {
                    b.Navigation("Registrations");
                });
#pragma warning restore 612, 618
        }
    }
}
