# 1. Установка базового образа
FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine

# 2. Установка рабочей директории
WORKDIR /app

# 3. Копирование .cproj файла
COPY Eventor.cproj src/backend/dotnet/Eventor.cproj  # TODO: изменить путь к файлу проекта 

# 4. Установка зависимостей
RUN dotnet restore Eventor.cproj --verbosity normal

# 5. Удаление .cproj файла
RUN rm Eventor.cproj