server {
        listen 80;              # слушаем порт 80
        root /var/www/html;     # корневая директория с файлами сайта
        index index.html;       # файл, который будет отдаваться для запроса "/"
}