POSTGRES_IMAGE=postgres:17
POSTGRES_DATA=postgres_data
POSTGRES_PORT=5432
POSTGRES_DB=eventor
POSTGRES_USER=postgres
POSTGRES_PASSWORD=postgres

PGADMIN_IMAGE=dpage/pgadmin4:9
PGADMIN_CONFIG=pgadmin
PGADMIN_DATA=pgadmin_data
PGADMIN_PORT=3002
PGADMIN_DEFAULT_EMAIL=admin@example.com
PGADMIN_DEFAULT_PASSWORD=admin

WEBSERVER_PORT=80

BACKEND_PORT=8081

COMPOSE_PROJECT_NAME=eventor-test-stand