name: Continuous Deployment (Test server)
env:
  CONTEXT_PATH: ../../..
  DOCKER_PATH: infra/production/docker
  BACKEND_PATH: src/backend/dotnet
  FRONTEND_PATH: src/frontend/angular
  WEBSERVER_PATH: shared/nginx

  POSTGRES_PORT: 5432
  POSTGRES_DB: eventor
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

  DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
  DOCKER_BACKEND_REPOSITORY: eventor-backend
  DOCKER_WEBSERVER_REPOSITORY: eventor-webserver
  DOCKER_BACKEND_CONTAINER: eventor-backend
  DOCKER_WEBSERVER_CONTAINER: eventor-webserver
  DOCKER_DATABASE_CONTAINER: eventor-database
  DOCKER_NETWORK: eventor-network

  SERVER_SSH_HOST: ${{ secrets.TEST_SERVER_SSH_HOST }}
  SERVER_SSH_PASSWORD: ${{ secrets.TEST_SERVER_SSH_PASSWORD }}
  SERVER_SSH_USER: ${{ secrets.TEST_SERVER_SSH_USER }}

  BACKEND_PORT: 8080
  NGINX_PORT: 80

on: [push]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_HUB_USER }}
          password: ${{ env.DOCKER_HUB_PASSWORD }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-docker-action@v4
        with:
          version: '29.2.1'

      - name: Verify Docker installation
        run: docker --version

      - name: Build backend image
        run: docker build -t ${{ env.DOCKER_HUB_USER }}/${{ env.DOCKER_BACKEND_REPOSITORY }}:latest -f ${{ env.DOCKER_PATH }}/dockerfile.backend ${{ env.CONTEXT_PATH }}

      - name: Push backend image to Docker Hub
        run: docker push ${{ env.DOCKER_HUB_USER }}/${{ env.DOCKER_BACKEND_REPOSITORY }}:latest

  build-webserver:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_HUB_USER }}
          password: ${{ env.DOCKER_HUB_PASSWORD }}
          
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-docker-action@v4
        with:
          version: '29.2.1'

      - name: Verify Docker installation
        run: docker --version

      - name: Build webserver image
        run: docker build -t ${{ env.DOCKER_HUB_USER }}/${{ env.DOCKER_WEBSERVER_REPOSITORY }}:latest -f ${{ env.DOCKER_PATH }}/dockerfile.web-server ${{ env.CONTEXT_PATH }}

      - name: Push webserver image to Docker Hub
        run: docker push ${{ env.DOCKER_HUB_USER }}/${{ env.DOCKER_WEBSERVER_REPOSITORY }}:latest

  deploy-database:
    runs-on: ubuntu-latest
    steps:
      - name: Pull and run database container
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ env.SERVER_SSH_HOST}}
          username: ${{ env.SERVER_SSH_USER }}
          password: ${{ env.SERVER_SSH_PASSWORD }}
          port: 22
          script: |
            docker run -d \
                       --name ${{ env.DOCKER_DATABASE_CONTAINER }} \
                       --network ${{ env.DOCKER_NETWORK }} \
                       -e POSTGRES_DB=${{ env.POSTGRES_DB }} \
                       -e POSTGRES_USER=${{ env.POSTGRES_USER }} \
                       -e POSTGRES_PASSWORD=${{ env.POSTGRES_PASSWORD }} \
                       -v postgres_data:/var/lib/postgresql/data \
                       postgres:17

  deploy-backend:
    needs: [build-backend, deploy-database]
    runs-on: ubuntu-latest
    steps:
      - name: Download backend image
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ env.SERVER_SSH_HOST}}
          username: ${{ env.SERVER_SSH_USER }}
          password: ${{ env.SERVER_SSH_PASSWORD}}
          port: 22
          script: docker pull ${{ env.DOCKER_HUB_USER }}/${{ env.DOCKER_BACKEND_REPOSITORY }}:latest

      - name: Stop backend container
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ env.SERVER_SSH_HOST}}
          username: ${{ env.SERVER_SSH_USER }}
          password: ${{ env.SERVER_SSH_PASSWORD}}
          port: 22
          script: docker stop ${{ env.DOCKER_BACKEND_CONTAINER }} || true
      
      - name: Remove backend container
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ env.SERVER_SSH_HOST}}
          username: ${{ env.SERVER_SSH_USER }}
          password: ${{ env.SERVER_SSH_PASSWORD}}
          port: 22
          script: docker rm ${{ env.DOCKER_BACKEND_CONTAINER }} || true

      - name: Run backend container
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ env.SERVER_SSH_HOST}}
          username: ${{ env.SERVER_SSH_USER }}
          password: ${{ env.SERVER_SSH_PASSWORD}}
          port: 22
          script: |
            docker run -d \
                       --name ${{ env.DOCKER_BACKEND_CONTAINER }} \
                       --network ${{ env.DOCKER_NETWORK }} \
                       -e "ConnectionStrings__Default=Host=${{ env.DOCKER_DATABASE_CONTAINER }};Database=${{ env.POSTGRES_DB }};Username=${{ env.POSTGRES_USER }};Password=${{ env.POSTGRES_PASSWORD }}" \
                       -p ${{ env.BACKEND_PORT }}:${{ env.BACKEND_PORT }} \
                        ${{ env.DOCKER_HUB_USER }}/${{ env.DOCKER_BACKEND_REPOSITORY }}:latest
      
  deploy-webserver:
    needs: build-webserver
    runs-on: ubuntu-latest
    steps:
      - name: Download web-server image
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ env.SERVER_SSH_HOST}}
          username: ${{ env.SERVER_SSH_USER }}
          password: ${{ env.SERVER_SSH_PASSWORD}}
          port: 22
          script: docker pull ${{ env.DOCKER_HUB_USER }}/${{ env.DOCKER_WEBSERVER_REPOSITORY }}:latest

      - name: Stop webserver container
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ env.SERVER_SSH_HOST}}
          username: ${{ env.SERVER_SSH_USER }}
          password: ${{ env.SERVER_SSH_PASSWORD}}
          port: 22
          script: docker stop ${{ env.DOCKER_WEBSERVER_CONTAINER }} || true

      - name: Remove webserver container
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ env.SERVER_SSH_HOST}}
          username: ${{ env.SERVER_SSH_USER }}
          password: ${{ env.SERVER_SSH_PASSWORD}}
          port: 22
          script: docker rm ${{ env.DOCKER_WEBSERVER_CONTAINER }} || true

      - name: Run webserver container
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ env.SERVER_SSH_HOST}}
          username: ${{ env.SERVER_SSH_USER }}
          password: ${{ env.SERVER_SSH_PASSWORD}}
          port: 22
          script: |
            docker run -d \
                       --name ${{ env.DOCKER_WEBSERVER_CONTAINER }} \
                       --network ${{ env.DOCKER_NETWORK }} \
                       -p ${{ env.NGINX_PORT }}:${{ env.NGINX_PORT }} \
                        ${{ env.DOCKER_HUB_USER }}/${{ env.DOCKER_WEBSERVER_REPOSITORY }}:latest
