name: Continuous Integration
env:
  CICD_PATH: infra/ci
  DOCKER_PATH: infra/ci/docker
  BACKEND_PATH: src/backend/dotnet
  FRONTEND_PATH: src/frontend/angular

  ENV_FILE: infra/ci/settings.conf
  DOCKER_COMPOSE_PATH: infra/ci/docker/docker-compose.yml
  POSTGRES_PORT: 5432
  POSTGRES_DB: eventor
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

on: [push]

jobs:
  build-database:
    name: Applying migrations to the database
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-docker-action@v4
        with:
          version: '29.2.1'

      - name: Verify Docker installation
        run: docker --version

      - name: Lifting the database container
        run: docker compose --env-file ${{ env.ENV_FILE }} -f ${{ env.DOCKER_COMPOSE_PATH }} up -d database --wait
    
      - name: Check database container status
        run: |
          status=$(docker inspect -f '{{.State.Status}}' database)
          if [ "$status" != "running" ]; then
            echo "Container is not running (status: $status)"
            exit 1
          fi

      - name: Check database container health
        run: |
          status=$(docker inspect -f '{{.State.Health.Status}}' database)
          if [ "$status" != "healthy" ]; then
            echo "Container is not healthy (status: $status)"
            exit 1
          fi

      - name: Lifting the backend container
        run: docker compose --env-file ${{ env.ENV_FILE }} -f ${{ env.DOCKER_COMPOSE_PATH }} up -d backend

      - name: Check backend container status
        run: |
          status=$(docker inspect -f '{{.State.Status}}' backend)
          if [ "$status" != "running" ]; then
            echo "Container is not running (status: $status)"
            exit 1
          fi

      - name: Build all projects in solution
        run: docker exec backend dotnet build Eventor.sln -c Debug --verbosity=normal

      - name: Run backend application and apply migrations
        run: docker exec -d backend dotnet run --project Web/Web.csproj --urls "http://0.0.0.0:8080" && sleep 10

      - name: Verify that __EFMigrationsHistory table exists
        run: |
          EXISTS=$(docker exec database psql -U ${{ env.POSTGRES_USER }} -d ${{ env.POSTGRES_DB }} -t -c "SELECT EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = '__EFMigrationsHistory');" | xargs)
          if [ "$EXISTS" != "t" ]; then
            echo "Table __EFMigrationsHistory not found!"
            exit 1
          fi
          echo "Table __EFMigrationsHistory exists. Migrations applied successfully."
  
  build-backend:
    name: Building a backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-docker-action@v4
        with:
          version: '29.2.1'

      - name: Verify Docker installation
        run: docker --version

      - name: Lifting the backend container
        run: docker compose --env-file ${{ env.ENV_FILE }} -f ${{ env.DOCKER_COMPOSE_PATH }} up -d backend

      - name: Check container status
        run: |
          status=$(docker inspect -f '{{.State.Status}}' backend)
          if [ "$status" != "running" ]; then
            echo "Container is not running (status: $status)"
            exit 1
          fi

      - name: Build all projects in solution
        run: docker exec backend dotnet build Eventor.sln -c Debug --verbosity=normal

  build-frontend:
    name: Building a frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-docker-action@v4
        with:
          version: '29.2.1'

      - name: Verify Docker installation
        run: docker --version

      - name: Lifting the frontend container
        run: docker compose --env-file ${{ env.ENV_FILE }} -f ${{ env.DOCKER_COMPOSE_PATH }} up -d frontend

      - name: Check container status
        run: |
          status=$(docker inspect -f '{{.State.Status}}' frontend)
          if [ "$status" != "running" ]; then
            echo "Container is not running (status: $status)"
            exit 1
          fi

      - name: Build project
        run: docker exec frontend sh -c "echo 'n' | npx ng build"

  build-webserver:
    name: Building a web-server
    needs: unit-tests-frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-docker-action@v4
        with:
          version: '29.2.1'

      - name: Verify Docker installation
        run: docker --version

      - name: Build web-server image
        run: docker compose --env-file ${{ env.ENV_FILE }} -f ${{ env.DOCKER_COMPOSE_PATH }} build web-server

  unit-tests-frontend:
    name: Running frontend unit tests
    needs: build-frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-docker-action@v4
        with:
          version: '29.2.1'

      - name: Verify Docker installation
        run: docker --version

      - name: Lifting the frontend container
        run: docker compose --env-file ${{ env.ENV_FILE }} -f ${{ env.DOCKER_COMPOSE_PATH }} up -d frontend

      - name: Check container status
        run: |
          status=$(docker inspect -f '{{.State.Status}}' frontend)
          if [ "$status" != "running" ]; then
            echo "Container is not running (status: $status)"
            exit 1
          fi

      - name: Run unit tests
        run: docker exec frontend sh -c "npx ng test"

  unit-tests-backend:
    name: Running backend unit tests
    needs: build-backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-docker-action@v4
        with:
          version: '29.2.1'

      - name: Verify Docker installation
        run: docker --version

      - name: Lifting the backend container
        run: docker compose --env-file ${{ env.ENV_FILE }} -f ${{ env.DOCKER_COMPOSE_PATH }} up -d backend

      - name: Check container status
        run: |
          status=$(docker inspect -f '{{.State.Status}}' backend)
          if [ "$status" != "running" ]; then
            echo "Container is not running (status: $status)"
            exit 1
          fi
      
      - name: Run unit tests
        run: docker exec backend dotnet test Eventor.sln -c Debug --filter "Category=Unit" --verbosity=normal

  integration-tests-backend:
    name: Running backend integration tests
    needs: [build-database, build-backend, unit-tests-backend]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-docker-action@v4
        with:
          version: '29.2.1'

      - name: Verify Docker installation
        run: docker --version

      - name: Lifting the database container
        run: docker compose --env-file ${{ env.ENV_FILE }} -f ${{ env.DOCKER_COMPOSE_PATH }} up -d database --wait
    
      - name: Check database container status
        run: |
          status=$(docker inspect -f '{{.State.Status}}' database)
          if [ "$status" != "running" ]; then
            echo "Container is not running (status: $status)"
            exit 1
          fi

      - name: Check database container health
        run: |
          status=$(docker inspect -f '{{.State.Health.Status}}' database)
          if [ "$status" != "healthy" ]; then
            echo "Container is not healthy (status: $status)"
            exit 1
          fi

      - name: Lifting the backend container
        run: docker compose --env-file ${{ env.ENV_FILE }} -f ${{ env.DOCKER_COMPOSE_PATH }} up -d backend

      - name: Check backend container status
        run: |
          status=$(docker inspect -f '{{.State.Status}}' backend)
          if [ "$status" != "running" ]; then
            echo "Container is not running (status: $status)"
            exit 1
          fi
      
      - name: Run integration tests
        run: docker exec backend dotnet test Eventor.sln -c Debug --filter "Category=Integration" --verbosity=normal

  e2e-tests-backend:
    name: Running backend end-to-end tests
    needs: [integration-tests-backend]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-docker-action@v4
        with:
          version: '29.2.1'

      - name: Verify Docker installation
        run: docker --version

      - name: Lifting the database container
        run: docker compose --env-file ${{ env.ENV_FILE }} -f ${{ env.DOCKER_COMPOSE_PATH }} up -d database --wait
    
      - name: Check database container status
        run: |
          status=$(docker inspect -f '{{.State.Status}}' database)
          if [ "$status" != "running" ]; then
            echo "Container is not running (status: $status)"
            exit 1
          fi

      - name: Check database container health
        run: |
          status=$(docker inspect -f '{{.State.Health.Status}}' database)
          if [ "$status" != "healthy" ]; then
            echo "Container is not healthy (status: $status)"
            exit 1
          fi

      - name: Lifting the backend container
        run: docker compose --env-file ${{ env.ENV_FILE }} -f ${{ env.DOCKER_COMPOSE_PATH }} up -d backend

      - name: Check backend container status
        run: |
          status=$(docker inspect -f '{{.State.Status}}' backend)
          if [ "$status" != "running" ]; then
            echo "Container is not running (status: $status)"
            exit 1
          fi
      
      - name: Run E2E tests
        run: docker exec backend dotnet test Eventor.sln -c Debug --filter "Category=E2E" --verbosity=normal

  run-backend:
    name: Running backend
    needs: [e2e-tests-backend]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Docker
        uses: docker/setup-docker-action@v4
        with:
          version: '29.2.1'

      - name: Verify Docker installation
        run: docker --version

      - name: Lifting the database container
        run: docker compose --env-file ${{ env.ENV_FILE }} -f ${{ env.DOCKER_COMPOSE_PATH }} up -d database --wait
    
      - name: Check database container status
        run: |
          status=$(docker inspect -f '{{.State.Status}}' database)
          if [ "$status" != "running" ]; then
            echo "Container is not running (status: $status)"
            exit 1
          fi

      - name: Check database container health
        run: |
          status=$(docker inspect -f '{{.State.Health.Status}}' database)
          if [ "$status" != "healthy" ]; then
            echo "Container is not healthy (status: $status)"
            exit 1
          fi

      - name: Lifting the backend container
        run: docker compose --env-file ${{ env.ENV_FILE }} -f ${{ env.DOCKER_COMPOSE_PATH }} up -d backend

      - name: Check backend container status
        run: |
          status=$(docker inspect -f '{{.State.Status}}' backend)
          if [ "$status" != "running" ]; then
            echo "Container is not running (status: $status)"
            exit 1
          fi

      - name: Run backend
        run: |
          docker exec -d backend dotnet run --project Web/Web.csproj -c Debug --urls "http://0.0.0.0:8080"
          sleep 15

      - name: Check backend API availability
        run: docker exec backend curl -f http://localhost:8080/

      - name: Check container health
        run: |
          status=$(docker inspect -f '{{.State.Health.Status}}' backend)
          if [ "$status" != "healthy" ]; then
            echo "Container is not healthy (status: $status)"
            exit 1
          fi

  run-webserver:
    name: Running web-server
    needs: build-webserver
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-docker-action@v4
        with:
          version: '29.2.1'

      - name: Verify Docker installation
        run: docker --version

      - name: Lifting the web-server container
        run: docker compose --env-file ${{ env.ENV_FILE }} -f ${{ env.DOCKER_COMPOSE_PATH }} up -d web-server --wait

      - name: Check container status
        run: |
          status=$(docker inspect -f '{{.State.Status}}' web-server)
          if [ "$status" != "running" ]; then
            echo "Container is not running (status: $status)"
            exit 1
          fi
      
      - name: Check container health
        run: |
          status=$(docker inspect -f '{{.State.Health.Status}}' web-server)
          if [ "$status" != "healthy" ]; then
            echo "Container is not healthy (status: $status)"
            exit 1
          fi